# permissions for end users to view autorestarts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: autorestart-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: auto-restart
    app.kubernetes.io/part-of: auto-restart
    app.kubernetes.io/managed-by: kustomize
  name: autorestart-viewer-role
rules:
- apiGroups:
  - apps.auto-restart
  resources:
  - autorestarts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.auto-restart
  resources:
  - autorestarts/status
  verbs:
  - get
